### ISSUE TITLE
AppImage support

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#2801]
**Describe your proposal**
Support AppImage distribution for Linux in CI.

**Additional context**
I have some test branch: https://github.com/Laserlicht/vcmi/tree/appimage
But no idea, why it's not working: https://github.com/Laserlicht/vcmi/actions/runs/6140058275/job/16658546576 (locally I was at least able to build appimage).

If someone want to try to get it ready feel free.

@Alexander-Wilms Do you have some experience in AppImage?

**Comment by IvanSavenko** [comment]
FYI - from my understanding, we'll need to also pack *all* our dependencies in addition to vcmi binaries - SDL, Qt, ffmpeg, likely - even libstdc++.

No idea if CMake provides support for such builds

**Comment by Laserlicht** [comment]
Yes, linuxdeploy should do the magic for this.

**Comment by Alexander-Wilms** [comment]
@Laserlicht No, I have not used AppImage.

**Comment by Laserlicht** [comment]
Update: Someone already tried it: https://github.com/AppImageCommunity/pkg2appimage/issues/294

By converting the DEB's into AppImage.

I've adjusted the script (vcmi.yml):
```
app: vcmi
 
ingredients:
  dist: lunar
  sources: 
    - deb https://ppa.launchpadcontent.net/vcmi/ppa/ubuntu lunar main
  ppas:
    - vcmi/vcmi-latest
 
script:
  - mv usr/lib/x86_64-linux-gnu/vcmi/* usr/lib/x86_64-linux-gnu/
  - mv usr/games/* usr/share/vcmi/* -t usr/bin
  - mv usr/lib/x86_64-linux-gnu/AI usr/bin/AI
  - sed -i -e 's#/usr#././#g' usr/bin/vcmiclient usr/bin/vcmilauncher usr/bin/vcmiserver usr/bin/vcmieditor
  - cp usr/share/applications/vcmilauncher.desktop vcmi.desktop
  - cp usr/share/icons/hicolor/scalable/apps/vcmiclient.svg vcmiclient.svg
```

can created with:
```
wget -c $(wget -q https://api.github.com/repos/AppImageCommunity/pkg2appimage/releases -O - | grep "pkg2appimage-.*-x86_64.AppImage" | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
chmod +x ./pkg2appimage-*.AppImage
./pkg2appimage-*.AppImage vcmi.yml
```

But there is one problem: The AI libs could not be loaded... (regardless which AI).
VCMI-Output:
`Cannot open dynamic link library (./AI/libVCAI.so). Throwing...`

Has someone any idea how to fix?
